### ISSUE TITLE
GC timing bug

### ISSUE THREAD

**Issue by YuyaAizawa** [carld/lispkit#1]
I found a bug that the GC collects "alloced and not linked to stack" cons-cell.
This happens, for example, when GC occurs during _ap.
https://github.com/carld/lispkit/blob/3ddbe431d9e093d2792f89a5b99aad811c1edba3/secd.c#L181
When center cons couse GC, cons-cell alloced by right cons is collected.

**Comment by carld** [comment]
Oh I see, good spotting.
Do you think the solution is to build that expression on the stack and later move it to the dump?:
``
_stack = cons( cons(cdr(cdr(_stack)),cons(_environ,cons(cdr(_control), _dump))) );
_dump = car( _stack );
_stack = cdr( _stack);
``
Thanks!

**Comment by YuyaAizawa** [comment]
It will not solve this problem, I think.
The root of this problem is where the GC occurs before the cons cell can be marked.
In above your code, cons cell made by `cons(cdr(_control), _dump)` can be gc when `cons(_environ,cons(cdr(_control), _dump))` is evaluate.

I wrote a workaround.

**Comment by carld** [comment]
Thanks for your help @YuyaAizawa ! I have merged this PR 👍
